// Cancel, Insert, Width, Height, Title, Text and Background are translated by Jodit
export default {
	// Dialog
	'Generate data': 'Daten generieren',
	Data: 'Daten',
	Template: 'Vorlage',
	Help: 'Hilfe',
	Type: 'Typ',
	Count: 'Anzahl',
	Layout: 'Layout',
	Shuffle: 'Mischen',
	'Choose other records': 'Andere Datensätze wählen',
	'1 to %s': '1 bis %s',
	'Text colour': 'Textfarbe',
	'Fields of the type': 'Felder des Typs',
	'Own template': 'Eigene Vorlage',
	Before: 'Davor',
	Item: 'Eintrag',
	After: 'Danach',
	'Before and After': 'Davor und Danach',
	'Insert into the template': 'In die Vorlage einfügen',
	Preview: 'Vorschau',
	'Loading data…': 'Daten werden geladen…',
	'The inserted content is regular content: it cannot be generated again. Check the preview.':
		'Der eingefügte Inhalt ist normaler Inhalt: Er kann nicht erneut generiert werden. Prüfen Sie die Vorschau.',

	// Help
	'Before is shown once, Item once for every generated item, After once at the end.':
		'„Davor“ erscheint einmal, „Eintrag“ für jeden generierten Datensatz, „Danach“ einmal am Ende.',
	Placeholders: 'Platzhalter',
	'%s — a field; the list on the Template tab shows the fields of the type':
		'%s — ein Feld; die Felder des Typs stehen auf dem Tab „Vorlage“',
	'%s — a field of a field': '%s — ein verschachteltes Feld',
	'%s — an item of a list, from 0': '%s — ein Element einer Liste, ab 0',
	'%s — a field of every item of a list': '%s — ein Feld jedes Elements einer Liste',
	'%s and %s — the number of the item and the number of items':
		'%s und %s — die Nummer des Datensatzes und die Anzahl der Datensätze',
	'%s — filters, applied from left to right': '%s — Filter, von links nach rechts angewendet',
	Filters: 'Filter',
	Rules: 'Regeln',
	'Values are escaped: the data cannot change the HTML of the template.':
		'Werte werden maskiert: Die Daten können das HTML der Vorlage nicht verändern.',
	'A list without a filter is shown with commas.': 'Eine Liste ohne Filter wird mit Kommas angezeigt.',
	'An empty field shows nothing; an unknown field or filter stops the insertion.':
		'Ein leeres Feld zeigt nichts; ein unbekanntes Feld oder ein unbekannter Filter verhindert das Einfügen.',
	'Tags that are not closed are only a warning: check the preview.':
		'Nicht geschlossene Tags sind nur eine Warnung: Prüfen Sie die Vorschau.',
	'Full documentation': 'Vollständige Dokumentation',

	// Filters
	'A bulleted list of the items': 'Eine Aufzählung der Elemente',
	'A numbered list of the items': 'Eine nummerierte Liste der Elemente',
	'The first item of a list': 'Das erste Element einer Liste',
	'The items joined with the argument, as written; a comma without it':
		'Die Elemente, verbunden mit dem Argument wie geschrieben; ohne Argument mit Komma',
	'The number of items': 'Die Anzahl der Elemente',
	'The first words of the text, with … when there are more': 'Die ersten Wörter des Textes, mit …, wenn es mehr gibt',
	'A number with the given number of decimals, 2 without the argument':
		'Eine Zahl mit der angegebenen Anzahl Nachkommastellen, ohne Argument 2',
	'The argument instead of an empty value': 'Das Argument statt eines leeren Werts',

	// Template problems
	'"{{" is not closed with "}}"': '„{{“ wird nicht mit „}}“ geschlossen',
	'%s is not a field name': '%s ist kein Feldname',
	'Unknown field %s': 'Unbekanntes Feld %s',
	'%s has fields, choose one: %s': '%s hat Felder, wählen Sie eines: %s',
	'Unknown filter %s': 'Unbekannter Filter %s',
	'The %s filter takes no argument': 'Der Filter %s nimmt kein Argument',
	'The %s filter needs an argument': 'Der Filter %s braucht ein Argument',
	'The %s filter needs a whole number from %s to %s': 'Der Filter %s braucht eine ganze Zahl von %s bis %s',
	'The %s filter must be the last one': 'Der Filter %s muss der letzte sein',
	'<%s> is not closed': '<%s> ist nicht geschlossen',
	'</%s> closes no tag': '</%s> schließt kein Tag',

	// Data service
	'The data service is not available': 'Der Datendienst ist nicht erreichbar',
	'The data service did not answer in time': 'Der Datendienst hat nicht rechtzeitig geantwortet',
	'The data service gave an unexpected answer': 'Der Datendienst hat eine unerwartete Antwort gegeben',

	// Types
	Posts: 'Beiträge',
	Quotes: 'Zitate',
	Comments: 'Kommentare',
	'To-dos': 'Aufgaben',
	Users: 'Benutzer',
	Products: 'Produkte',
	Reviews: 'Bewertungen',
	Recipes: 'Rezepte',
	Order: 'Bestellung',
	Images: 'Bilder',

	// Descriptions of the types
	'Short stories with a title, one paragraph of text, tags and reactions.':
		'Kurze Geschichten mit Titel, einem Absatz Text, Tags und Reaktionen.',
	'Quotes of famous people with their authors.':
		'Zitate berühmter Menschen mit ihren Autoren.',
	'One-sentence comments with the name of the author and the likes.':
		'Kommentare aus einem Satz mit dem Namen des Autors und den Likes.',
	'Tasks that are done or not, for lists and checklists.':
		'Erledigte und offene Aufgaben, für Listen und Checklisten.',
	'People: name, age, email, phone, avatar, address, company and job. No private data is asked for.':
		'Personen: Name, Alter, E-Mail, Telefon, Avatar, Adresse, Firma und Position. Private Daten werden nicht abgefragt.',
	'Products with a description, price, discount, rating, brand, pictures and reviews. The pictures are links to cdn.dummyjson.com.':
		'Produkte mit Beschreibung, Preis, Rabatt, Bewertung, Marke, Bildern und Bewertungen. Die Bilder sind Links zu cdn.dummyjson.com.',
	'Reviews of the products: rating, text, the name of the reviewer and the product.':
		'Bewertungen der Produkte: Note, Text, Name des Bewertenden und das Produkt.',
	'Recipes with a picture, ingredients, steps, time, servings and calories. There are 50 of them.':
		'Rezepte mit Bild, Zutaten, Schritten, Zeit, Portionen und Kalorien. Es gibt 50 davon.',
	'An order of random products, each with a quantity from 1 to 5, and its totals: for an invoice or a receipt.':
		'Eine Bestellung zufälliger Produkte, jeweils mit einer Menge von 1 bis 5, und ihre Summen: für eine Rechnung oder einen Beleg.',
	'Placeholder images of the size, colours and text you set, as links to the data service.':
		'Platzhalterbilder in der gewählten Größe, mit Farben und Text, als Links zum Datendienst.',

	// Layouts
	'Headings and paragraphs': 'Überschriften und Absätze',
	Paragraphs: 'Absätze',
	List: 'Liste',
	Checklist: 'Checkliste',
	'Numbered list': 'Nummerierte Liste',
	Table: 'Tabelle',
	Cards: 'Karten',
	'Cards with reviews': 'Karten mit Bewertungen',
	'Full recipes': 'Vollständige Rezepte',
	'One per paragraph': 'Eines pro Absatz',
	'In one paragraph': 'In einem Absatz',

	// Fields
	'Number of generated items': 'Anzahl der generierten Datensätze',
	'Number of the item, from 1': 'Nummer des Datensatzes, ab 1',
	'Number of the record in the service': 'Nummer des Datensatzes im Dienst',
	'Text, one paragraph': 'Text, ein Absatz',
	Tags: 'Tags',
	'Number of views': 'Anzahl der Aufrufe',
	'Number of likes': 'Anzahl der Likes',
	'Number of dislikes': 'Anzahl der Dislikes',
	'Text of the quote': 'Text des Zitats',
	Author: 'Autor',
	'Text, one sentence': 'Text, ein Satz',
	'Name of the author': 'Name des Autors',
	'Username of the author': 'Benutzername des Autors',
	Task: 'Aufgabe',
	'Done: true or false': 'Erledigt: true oder false',
	'Checkbox: ☑ when done, ☐ when not': 'Kontrollkästchen: ☑ erledigt, ☐ offen',
	'First name': 'Vorname',
	'Last name': 'Nachname',
	'First and last name': 'Vor- und Nachname',
	'Maiden name': 'Geburtsname',
	Age: 'Alter',
	'Gender: male or female': 'Geschlecht: male oder female',
	'Date of birth, like 1996-5-30': 'Geburtsdatum, z. B. 1996-5-30',
	'Email address': 'E-Mail-Adresse',
	'Phone number': 'Telefonnummer',
	Username: 'Benutzername',
	'URL of the avatar, 128×128': 'URL des Avatars, 128×128',
	'Role: admin, moderator or user': 'Rolle: admin, moderator oder user',
	University: 'Universität',
	'Blood group': 'Blutgruppe',
	'Height, cm': 'Größe, cm',
	'Weight, kg': 'Gewicht, kg',
	'Eye colour': 'Augenfarbe',
	'Hair colour': 'Haarfarbe',
	'Hair type': 'Haartyp',
	'Street address': 'Straße und Hausnummer',
	City: 'Stadt',
	State: 'Bundesstaat',
	'State code': 'Kürzel des Bundesstaats',
	'Postal code': 'Postleitzahl',
	Country: 'Land',
	Latitude: 'Breitengrad',
	Longitude: 'Längengrad',
	Company: 'Firma',
	'Job title': 'Position',
	Department: 'Abteilung',
	'Street address of the company': 'Straße und Hausnummer der Firma',
	'City of the company': 'Stadt der Firma',
	'State of the company': 'Bundesstaat der Firma',
	'State code of the company': 'Kürzel des Bundesstaats der Firma',
	'Postal code of the company': 'Postleitzahl der Firma',
	'Country of the company': 'Land der Firma',
	'Latitude of the company': 'Breitengrad der Firma',
	'Longitude of the company': 'Längengrad der Firma',
	Name: 'Name',
	Description: 'Beschreibung',
	Category: 'Kategorie',
	'Brand; not every product has one': 'Marke; nicht jedes Produkt hat eine',
	Price: 'Preis',
	'Discount, %': 'Rabatt, %',
	'Price with the discount': 'Preis mit Rabatt',
	'Rating from 0 to 5': 'Bewertung von 0 bis 5',
	'Rating as stars: ★★★★☆': 'Bewertung als Sterne: ★★★★☆',
	'Number in stock': 'Lagerbestand',
	'In Stock or Low Stock': 'In Stock oder Low Stock',
	'Stock keeping unit': 'Artikelnummer',
	Weight: 'Gewicht',
	Depth: 'Tiefe',
	Warranty: 'Garantie',
	Shipping: 'Versand',
	'Return policy': 'Rückgaberecht',
	'Minimum order quantity': 'Mindestbestellmenge',
	'URL of the small picture': 'URL des kleinen Bildes',
	'URLs of the pictures': 'URLs der Bilder',
	'Ratings of the reviews': 'Noten der Bewertungen',
	'Texts of the reviews': 'Texte der Bewertungen',
	'Dates of the reviews': 'Daten der Bewertungen',
	'Names of the reviewers': 'Namen der Bewertenden',
	'Rating from 1 to 5': 'Note von 1 bis 5',
	'Text of the review': 'Text der Bewertung',
	'Date and time, ISO 8601': 'Datum und Uhrzeit, ISO 8601',
	'Name of the reviewer': 'Name des Bewertenden',
	'Number of the product': 'Nummer des Produkts',
	'Name of the product': 'Name des Produkts',
	'URL of the small picture of the product': 'URL des kleinen Bildes des Produkts',
	'URL of the picture': 'URL des Bildes',
	Ingredients: 'Zutaten',
	Steps: 'Schritte',
	'Preparation time, minutes': 'Vorbereitungszeit, Minuten',
	'Cooking time, minutes': 'Kochzeit, Minuten',
	'Number of servings': 'Anzahl der Portionen',
	'Easy, Medium or Hard': 'Easy, Medium oder Hard',
	Cuisine: 'Küche',
	'Calories per serving': 'Kalorien pro Portion',
	'Number of reviews': 'Anzahl der Bewertungen',
	'Meals: Breakfast, Lunch, Dinner…': 'Mahlzeiten: Breakfast, Lunch, Dinner…',
	'Price of one': 'Stückpreis',
	'Quantity, from 1 to 5': 'Menge, von 1 bis 5',
	'Price × quantity': 'Preis × Menge',
	'Total of the order': 'Summe der Bestellung',
	'Number of all products in the order': 'Anzahl aller Produkte der Bestellung',
	'URL of the image': 'URL des Bildes',
	'Width, px': 'Breite, px',
	'Height, px': 'Höhe, px',
	'Background colour, like 5b8def': 'Hintergrundfarbe, z. B. 5b8def',
	'Text colour, like ffffff': 'Textfarbe, z. B. ffffff'
};
