// Cancel, Insert, Width, Height, Title, Text and Background are translated by Jodit
export default {
	// Dialog
	'Generate data': 'Сгенерировать данные',
	Data: 'Данные',
	Template: 'Шаблон',
	Help: 'Справка',
	Type: 'Тип',
	Count: 'Количество',
	Layout: 'Разметка',
	Shuffle: 'Перемешать',
	'Choose other records': 'Выбрать другие записи',
	'1 to %s': 'от 1 до %s',
	'Text colour': 'Цвет текста',
	'Own template': 'Свой шаблон',
	Before: 'До',
	Item: 'Элемент',
	After: 'После',
	'Before and After': 'До и После',
	'Insert into the template': 'Вставить в шаблон',
	Preview: 'Предпросмотр',
	'Loading data…': 'Загрузка данных…',
	'The inserted content is regular content: it cannot be generated again. Check the preview.':
		'Вставленное содержимое — обычный контент: сгенерировать его заново будет нельзя. Проверьте предпросмотр.',

	// Help
	'Before is shown once, Item once for every generated item, After once at the end.':
		'«До» выводится один раз, «Элемент» — для каждой сгенерированной записи, «После» — один раз в конце.',
	Placeholders: 'Плейсхолдеры',
	'%s — a field; the list on the Template tab shows the fields of the type':
		'%s — поле; поля типа перечислены на вкладке «Шаблон»',
	'%s — a field of a field': '%s — вложенное поле',
	'%s — an item of a list, from 0': '%s — элемент списка, с 0',
	'%s — a field of every item of a list': '%s — поле каждого элемента списка',
	'%s and %s — the number of the item and the number of items': '%s и %s — номер записи и число записей',
	'%s — filters, applied from left to right': '%s — фильтры, применяются слева направо',
	Filters: 'Фильтры',
	Rules: 'Правила',
	'Values are escaped: the data cannot change the HTML of the template.':
		'Значения экранируются: данные не могут изменить HTML шаблона.',
	'A list without a filter is shown with commas.': 'Список без фильтра выводится через запятую.',
	'An empty field shows nothing; an unknown field or filter stops the insertion.':
		'Пустое поле ничего не выводит; неизвестное поле или фильтр не дают вставить результат.',
	'Tags that are not closed are only a warning: check the preview.':
		'Незакрытые теги — только предупреждение: проверьте предпросмотр.',
	'Full documentation': 'Полная документация',

	// Filters
	'A bulleted list of the items': 'Маркированный список элементов',
	'A numbered list of the items': 'Нумерованный список элементов',
	'The first item of a list': 'Первый элемент списка',
	'The items joined with the argument, as written; a comma without it':
		'Элементы через аргумент, как он написан; без аргумента — через запятую',
	'The number of items': 'Число элементов',
	'The first words of the text, with … when there are more': 'Первые слова текста и …, если слов больше',
	'A number with the given number of decimals, 2 without the argument':
		'Число с заданным числом знаков после точки, без аргумента — 2',
	'The argument instead of an empty value': 'Аргумент вместо пустого значения',

	// Template problems
	'"{{" is not closed with "}}"': '«{{» не закрыта «}}»',
	'%s is not a field name': '%s — не имя поля',
	'Unknown field %s': 'Неизвестное поле %s',
	'%s has fields, choose one: %s': 'У %s есть поля, выберите одно: %s',
	'Unknown filter %s': 'Неизвестный фильтр %s',
	'The %s filter takes no argument': 'Фильтр %s не принимает аргумент',
	'The %s filter needs an argument': 'Фильтру %s нужен аргумент',
	'The %s filter needs a whole number from %s to %s': 'Фильтру %s нужно целое число от %s до %s',
	'The %s filter must be the last one': 'Фильтр %s должен быть последним',
	'<%s> is not closed': '<%s> не закрыт',
	'</%s> closes no tag': '</%s> не закрывает ни один тег',

	// Data service
	'The data service is not available': 'Сервис данных недоступен',
	'The data service did not answer in time': 'Сервис данных не ответил вовремя',
	'The data service gave an unexpected answer': 'Сервис данных вернул неожиданный ответ',

	// Types
	Posts: 'Посты',
	Quotes: 'Цитаты',
	Comments: 'Комментарии',
	'To-dos': 'Задачи',
	Users: 'Пользователи',
	Products: 'Товары',
	Reviews: 'Отзывы',
	Recipes: 'Рецепты',
	Order: 'Заказ',
	Images: 'Изображения',

	// Layouts
	'Headings and paragraphs': 'Заголовки и абзацы',
	Paragraphs: 'Абзацы',
	List: 'Список',
	Checklist: 'Чек-лист',
	'Numbered list': 'Нумерованный список',
	Table: 'Таблица',
	Cards: 'Карточки',
	'Cards with reviews': 'Карточки с отзывами',
	'Full recipes': 'Рецепты целиком',
	'One per paragraph': 'По одному в абзаце',
	'In one paragraph': 'В одном абзаце',

	// Fields
	'Number of generated items': 'Число сгенерированных записей',
	'Number of the item, from 1': 'Номер записи, с 1',
	'Number of the record in the service': 'Номер записи в сервисе',
	'Text, one paragraph': 'Текст, один абзац',
	Tags: 'Теги',
	'Number of views': 'Число просмотров',
	'Number of likes': 'Число лайков',
	'Number of dislikes': 'Число дизлайков',
	'Text of the quote': 'Текст цитаты',
	Author: 'Автор',
	'Text, one sentence': 'Текст, одно предложение',
	'Name of the author': 'Имя автора',
	'Username of the author': 'Логин автора',
	Task: 'Задача',
	'Done: true or false': 'Выполнена: true или false',
	'Checkbox: ☑ when done, ☐ when not': 'Флажок: ☑ — выполнена, ☐ — нет',
	'First name': 'Имя',
	'Last name': 'Фамилия',
	'First and last name': 'Имя и фамилия',
	'Maiden name': 'Девичья фамилия',
	Age: 'Возраст',
	'Gender: male or female': 'Пол: male или female',
	'Date of birth, like 1996-5-30': 'Дата рождения, например 1996-5-30',
	'Email address': 'Адрес эл. почты',
	'Phone number': 'Номер телефона',
	Username: 'Логин',
	'URL of the avatar, 128×128': 'URL аватара, 128×128',
	'Role: admin, moderator or user': 'Роль: admin, moderator или user',
	University: 'Университет',
	'Blood group': 'Группа крови',
	'Height, cm': 'Рост, см',
	'Weight, kg': 'Вес, кг',
	'Eye colour': 'Цвет глаз',
	'Hair colour': 'Цвет волос',
	'Hair type': 'Тип волос',
	'Street address': 'Улица и дом',
	City: 'Город',
	State: 'Штат',
	'State code': 'Код штата',
	'Postal code': 'Почтовый индекс',
	Country: 'Страна',
	Latitude: 'Широта',
	Longitude: 'Долгота',
	Company: 'Компания',
	'Job title': 'Должность',
	Department: 'Отдел',
	'Street address of the company': 'Улица и дом компании',
	'City of the company': 'Город компании',
	'State of the company': 'Штат компании',
	'State code of the company': 'Код штата компании',
	'Postal code of the company': 'Почтовый индекс компании',
	'Country of the company': 'Страна компании',
	'Latitude of the company': 'Широта компании',
	'Longitude of the company': 'Долгота компании',
	Name: 'Название',
	Description: 'Описание',
	Category: 'Категория',
	'Brand; not every product has one': 'Бренд; есть не у всех товаров',
	Price: 'Цена',
	'Discount, %': 'Скидка, %',
	'Price with the discount': 'Цена со скидкой',
	'Rating from 0 to 5': 'Рейтинг от 0 до 5',
	'Rating as stars: ★★★★☆': 'Рейтинг звёздами: ★★★★☆',
	'Number in stock': 'Количество на складе',
	'In Stock or Low Stock': 'In Stock или Low Stock',
	'Stock keeping unit': 'Артикул',
	Weight: 'Вес',
	Depth: 'Глубина',
	Warranty: 'Гарантия',
	Shipping: 'Доставка',
	'Return policy': 'Условия возврата',
	'Minimum order quantity': 'Минимальный заказ',
	'URL of the small picture': 'URL маленькой картинки',
	'URLs of the pictures': 'URL картинок',
	'Ratings of the reviews': 'Оценки отзывов',
	'Texts of the reviews': 'Тексты отзывов',
	'Dates of the reviews': 'Даты отзывов',
	'Names of the reviewers': 'Имена авторов отзывов',
	'Rating from 1 to 5': 'Оценка от 1 до 5',
	'Text of the review': 'Текст отзыва',
	'Date and time, ISO 8601': 'Дата и время, ISO 8601',
	'Name of the reviewer': 'Имя автора отзыва',
	'Number of the product': 'Номер товара',
	'Name of the product': 'Название товара',
	'URL of the small picture of the product': 'URL маленькой картинки товара',
	'URL of the picture': 'URL картинки',
	Ingredients: 'Ингредиенты',
	Steps: 'Шаги',
	'Preparation time, minutes': 'Подготовка, минут',
	'Cooking time, minutes': 'Приготовление, минут',
	'Number of servings': 'Число порций',
	'Easy, Medium or Hard': 'Easy, Medium или Hard',
	Cuisine: 'Кухня',
	'Calories per serving': 'Калорий на порцию',
	'Number of reviews': 'Число отзывов',
	'Meals: Breakfast, Lunch, Dinner…': 'Приёмы пищи: Breakfast, Lunch, Dinner…',
	'Price of one': 'Цена за штуку',
	'Quantity, from 1 to 5': 'Количество, от 1 до 5',
	'Price × quantity': 'Цена × количество',
	'Total of the order': 'Сумма заказа',
	'Number of all products in the order': 'Всего товаров в заказе',
	'URL of the image': 'URL изображения',
	'Width, px': 'Ширина, px',
	'Height, px': 'Высота, px',
	'Background colour, like 5b8def': 'Цвет фона, например 5b8def',
	'Text colour, like ffffff': 'Цвет текста, например ffffff'
};
